<?php

/**
 * @package BrandsCustomPostType
 * @author Waqar Haider <waqarhaider783@yahoo.com>
 * @copyright 2021 Va8ive Digital
 * @license GPL-2.0-or-later
 * 
 * Plugin Name: Brands Custom Post Type
 * Description: This is a custom plugin developed for Shaping Nutrition that adds a custom post type with the name "Brands" that builds and maintains relationships with the Products Custom Post Type automatically added by Woocommerce. This plugin requires the free or PRO version of ACF to be installed as well as WooCommerce.
 * Version: 0.0.1
 * Author: Waqar Haider
 * Author URI: https://va8ivedigital.com/
 * Text Domain: brands=custom-post-type
 */

/*
 * Brands Custom Post Type is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * any later version.
 * 
 * Brands Custom Post Type is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
*/

/**
 * Security Measure
 */
if(!defined('ABSPATH')) exit;

$required_plugins_are_active = false;

/**
 * Check active plugins
 */
function v8_check_active_plugins() {

  global $required_plugins_are_active;

  $plugins = array(
    'woocommerce' => array(
      'name'      => 'WooCommerce',
      'function'       => 'wc_get_product'
    ),
    'acf'         => array(
      'name'      => 'Advanced Custom Fields',
      'function'       => 'the_field'
    )
  );

  $inactive_plugins = array();

  foreach($plugins as $plugin) {
    if(!function_exists($plugin['function'])) array_push($inactive_plugins, $plugin['name']);
  }

  if(sizeof($inactive_plugins)) :

    $error_notice = new WP_Error('broke', __('Brands Custom Post Type requires the following plugins to be active: ' . implode(', ', $inactive_plugins) . '. Please install or activate them and then use this plugin.', 'brands-custom-post-type'));
    ?>
    <div class="notice error is-dismissable">
      <p>
        <?php echo $error_notice->get_error_message(); ?>
      </p>
    </div>
    <?php

  endif;

  unset ($inactive_plugins, $error_notice, $plugins);

  $required_plugins_are_active = true;
  
  return;

}

/**
 * Add fields generated by ACF to the post type automatically
 */
require_once __DIR__ . '/includes/fields-brand.php';
require_once __DIR__ . '/includes/fields-product.php';
require_once __DIR__ . '/includes/on-product-save.php';
require_once __DIR__ . '/includes/ajax/ajax-admin-sync.php';

/**
 * Register the Custom Post Type
 */
require_once __DIR__ . '/includes/registration.php';

/**
 * Add the plugin checker function to the WP loop
 */
add_action('admin_init', 'v8_check_active_plugins');

/**
 * Add the custom post type to the WP loop
 */
add_action('init', 'v8_init_brands_post_type');
/**
 * Add the custom post type to the WP loop
 */
add_action('admin_footer', 'v8_add_sync_button');

/**
 * Add the single page template for brands to the WP loop
 */
add_filter('single_template', 'v8_single_post_template');

/**
 * Insert the populate_brands_in_woocommerce function into the ACF loop
 */
add_filter('acf/load_field/name=brand', 'populate_brands_in_woocommerce');

/**
 * Function to enqueue scripts and styles for the plugin
 */
function v8_enqueue_scripts_and_styles() {
  /**
   * General theme styles
   */
  wp_enqueue_style('brand-styles', plugin_dir_url(__FILE__) . 'style.css');
}

/**
 * Add plugin scripts and styles to the WP loop
 */
add_action('wp_enqueue_scripts', 'v8_enqueue_scripts_and_styles');

/**
 * AJAX function registration
 */
add_action('wp_ajax_sync_brand_categories', 'v8_admin_ajax_sync');

/**
 * Auto-add new product categories to brands when products
 * are saved.
 */
add_action('save_post_product', 'update_brand_categories_on_product_save', 10, 3);